name: Minecraft Server CI/CD

# トリガー: mainブランチにプッシュされた時に実行
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. ソースコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Docker Hubへのログイン
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Dockerイメージのビルドとプッシュ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/minecraft-server:latest # latestタグを付けてプッシュ

  deploy:
    # build-and-pushジョブが成功したら実行
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # 1. SSH経由でデプロイコマンドを実行
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # サーバー上のdocker-compose.ymlがあるディレクトリに移動
            cd /path/to/your/minecraft-server 
            
            # Docker Hubから最新のイメージを取得
            docker compose pull
            
            # 新しいイメージでコンテナを再起動
            docker compose up -d
            
            # 古い不要なイメージを削除
            docker image prune -f