# .github/workflows/cicd.yml

name: Minecraft Server CI/CD for Argo CD

# トリガー: mainブランチにプッシュされた時に実行
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # ジョブの結果（イメージタグ）を他のジョブで使えるようにoutputsを設定
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Gitのコミットハッシュからユニークなタグを生成するステップ
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/minecraft-server
          tags: |
            type=sha,prefix=,format=short

      # ビルドとプッシュ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 生成されたユニークなタグ (例: 1a2b3c4) と latest タグを付ける
          tags: ${{ steps.meta.outputs.tags }}, ${{ secrets.DOCKERHUB_USERNAME }}/minecraft-server:latest
          labels: ${{ steps.meta.outputs.labels }}

  # SSHでデプロイする代わりにマニフェストを更新するジョブ
  update-manifest:
    runs-on: ubuntu-latest
    # build-and-pushジョブが成功したら実行
    needs: build-and-push
    steps:
      # 1. Kubernetesマニフェストのリポジトリをチェックアウト
      - name: Checkout manifests repository
        uses: actions/checkout@v4
        with:
          # ここにマニフェストを管理しているリポジトリを指定
          repository: RyoNagashiro9280/k8s-manifest
          # マニフェストリポジトリにプッシュするためのトークン
          token: ${{ secrets.MANIFEST_REPO_ACCESS_TOKEN }}

      # 2. deployment.yamlのイメージタグを更新
      # yqを使うと安全にYAMLを編集できる
      - name: Update image tag in deployment.yaml
        uses: mikefarah/yq@v4
        with:
          cmd: yq -i '.spec.template.spec.containers[0].image = "${{ secrets.DOCKERHUB_USERNAME }}/minecraft-server:${{ needs.build-and-push.outputs.image_tag }}"' 'mc-chart/deployment.yaml'

      # 3. 変更をコミットしてプッシュ
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # ▼▼▼▼▼ ここのパスを修正しました ▼▼▼▼▼
          git add mc-chart/deployment.yaml
          # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
          # 変更があった場合のみコミット
          git diff --staged --quiet || git commit -m "Update image tag to ${{ needs.build-and-push.outputs.image_tag }}"
          git push
